version: "3"
services:
  collector:
    image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.71.0
    command: ["--config=/conf/collector-config.yaml"]
    volumes:
      - ./collector-config.yaml:/conf/collector-config.yaml
    ports:
      - "9464:9464"
      - "4317:4317"
      - "4318:4318"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:1.42.0
    ports:
        - "16686:16686"
